services:
  postgres:
    image: postgres:15
    container_name: deacons_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: deacons_school
    ports:
      - "5433:5432" # التغيير هنا (الرقم الأيسر أصبح 5433)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
